Use defineJahiaComponents everywhere
Jahia/npm-solid-react-templateset-example pull request #15
Opened 2024-07-22 11:01 UTC by TimRobertDev

2024-07-24 12:50 UTC, jkevan requested changes

2024-07-24 12:50 UTC, jkevan commented on src/server/views/hello/HelloDefault.jsx
> +    name: 'Hello', // The display name of the view
This is wrong, the `name` is not the `displayName`
It's actually a technical name, and should be 'default' in case it was not define before.

2024-07-24 12:50 UTC, jkevan commented on src/server/views/featureSection/FeatureSectionDefault.jsx
> +    name: 'Feature-section',
This is wrong, the `name` is not the `displayName`
It's actually a technical name, and should be 'default' in case it was not define before.

2024-07-24 12:50 UTC, jkevan commented on src/server/views/feature/FeatureDefault.jsx
> +    name: 'Feature',
This is wrong, the `name` is not the `displayName`
It's actually a technical name, and should be 'default' in case it was not define before.

2024-07-24 12:50 UTC, jkevan commented on src/server/views/ctaSection/CtaSectionDefault.jsx
> +});
is it not missing name ?

2024-07-24 12:50 UTC, jkevan commented on src/server/views/pricingSection/PricingSectionDefault.jsx
> +});
missing name ?

2024-07-24 12:50 UTC, jkevan commented on src/server/views/pricingTier/PricingTierDefault.jsx
> +});
missing name ?

2024-07-24 13:26 UTC, TimRobertDev commented on src/server/views/hello/HelloDefault.jsx
> +    name: 'Hello', // The display name of the view
Okay I didn't know thank you, I'll add it everywhere

2024-07-24 13:27 UTC, TimRobertDev commented on src/server/views/featureSection/FeatureSectionDefault.jsx
> +    name: 'Feature-section',
Modified

2024-07-24 13:27 UTC, TimRobertDev commented on src/server/views/feature/FeatureDefault.jsx
> +    name: 'Feature',
Modified

2024-07-24 13:28 UTC, TimRobertDev commented on src/server/views/ctaSection/CtaSectionDefault.jsx
> +});
Modified

2024-07-24 13:28 UTC, TimRobertDev commented on src/server/views/pricingSection/PricingSectionDefault.jsx
> +});
Modified

2024-07-24 13:28 UTC, TimRobertDev commented on src/server/views/pricingTier/PricingTierDefault.jsx
> +});
Modified

2024-07-29 08:35 UTC, jkevan approved these changes

2024-07-29 08:35 UTC, merged